# Generated by Django 4.1.7 on 2023-04-05 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('washbooking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='association',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
