# Generated by Django 4.1.7 on 2023-04-05 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('washbooking', '0002_association_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='association',
        ),
        migrations.RemoveField(
            model_name='person',
            name='birthdate',
        ),
        migrations.AddField(
            model_name='person',
            name='inAssociation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='washbooking.association'),
        ),
    ]
