# Generated by Django 4.1.7 on 2023-04-05 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('washbooking', '0004_remove_person_inassociation_person_associations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='associations',
        ),
        migrations.AddField(
            model_name='person',
            name='assocation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='washbooking.association'),
        ),
    ]
