# Generated by Django 4.1.7 on 2023-04-07 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('washbooking', '0005_remove_person_associations_person_assocation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='assocation',
        ),
        migrations.AddField(
            model_name='person',
            name='associations',
            field=models.ManyToManyField(to='washbooking.association'),
        ),
    ]
