# Generated by Django 4.1.7 on 2023-04-08 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('washbooking', '0007_bookedtime_booked_by_bookedtime_booking_object_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BookedTime',
        ),
    ]
