# Generated by Django 4.1.7 on 2023-04-08 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('washbooking', '0008_delete_bookedtime'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookedTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeslot', models.IntegerField(choices=[(0, '06:00 - 10:00'), (1, '10:00 - 14:00'), (2, '14:00 - 18:00'), (3, '18:00 - 22:00')], null=True)),
                ('date', models.DateField(help_text='YYYY-MM-DD', null=True)),
                ('booked_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='washbooking.person')),
                ('booking_object', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='washbooking.bookableobject')),
            ],
            options={
                'unique_together': {('timeslot', 'date')},
            },
        ),
    ]
